name: ci-pr

on:
    push:
      branches:
        - main
    pull_request:

env: 
    IMAGE_NAME: jlp04/elevation-generator

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.repository_owner }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Get Git commit timestamps
              run: echo "TIMESTAMP=$(ls && pwd && git log -1 --pretty=%ct)"

            - name: Get Git Indeterminate Branch
              run: echo "BRANCH_END=$(git ls-remote --heads "https://gitlab.com/flightgear/flightgear.git" | sed -nEe 's@.*[ \t]+refs/heads/release/([^ \t]+)@\1@p' | sort -t . -k 1,1n -k2,2n -k3,3n | tail -1)" >> $GITHUB_ENV

            - name: Validate build configuration
              uses: docker/bake-action@v6
              with:
                targets: validate-build
                set: "default.args.branch_end= ${{ env.BRANCH_END }}"
              env: 
                SOURCE_DATE_EPOCH: ${{ env.TIMESTAMP }}

            - name: Build
              uses: docker/bake-action@v6
              with:
                targets: default
                set: "default.args.branch_end= ${{ env.BRANCH_END }}"
                push: true
                provenance: true
                sbom: true
              env: 
                SOURCE_DATE_EPOCH: ${{ env.TIMESTAMP }}