name: ci-push

on:
    pull_request_target:
        types:
            - labeled

env: 
    IMAGE_NAME: jlp04/elevation-generator

jobs:
    docker:
        if: contains(github.event.pull_request.labels.*.name, 'pr-pull')
        runs-on: ubuntu-latest
        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}
                
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.repository_owner }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Push Image to Docker Hub
              run: |
                docker buildx imagetools create \
                --tag jlp04/elevation-generator:test \
                ghcr.io/jlp04/elevation-generator:test

            - name: Scout
              uses: docker/scout-action@v1
              with:
                command: quickview,cves,recommendations
                image: jlp04/elevation-generator:test
                platform: all
                sarif-file: sarif.output.json

            - name: Upload SARIF Results
              id: upload-sarif
              uses: github/codeql-action/upload-sarif@v2
              with: 
                sarif_file: sarif.output.json